# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef9e1d19a2fd433a2f0c3678f76033f3b9c4e0d190428dd67f3bfb50b618993063bfd45461196eb14421223c8df0f969e2d88bc604d8c2795bf09dddf4a9f42a

test:
  secret_key_base: aa62617e04361c93124efa363a8be1538ba17f33f75345eaccfadb711e3ee890e121f0409b61b7a078786ff1f5a89a347fbcec85671a45699aa3afd120020fad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
